### ISSUE TITLE
Ant task.properties

### ISSUE THREAD

**Issue by giangiunta** [Guardsquare/proguard#52]
Hi all,
I've been using proguard for years in Eclipse projects with Ant task.
It seems like ant folder and task.properties haven't been included in the proguard.jar version 7.0.0.

<taskdef resource="proguard/ant/task.properties"
         classpath="/mylib_path/proguard.jar" />

[taskdef] Could not load definitions from resource proguard/ant/task.properties. It could not be found.

Is Ant task supported in proguard 7?

Best Regards

Gianluca

**Comment by EricSalemi** [comment]
Ant task is supported is version 7.0.0.

Are you depending on the `com.guardsquare:proguard-ant:7.0.0` artifact?

**Comment by giangiunta** [comment]
I've extracted proguard.jar from proguard-7.0.0.zip

https://github.com/Guardsquare/proguard/releases/tag/v7.0.0

**Comment by rjahn** [comment]
Same here, no ant package in jar file available!

**Comment by EricLafortune** [comment]
ProGuard 7.0.0 accidentally does not contain the Ant plugin in `lib/proguard.jar`. We'll fix this in an update. For the time being, you can download [proguard-ant-7.0.0.jar](https://bintray.com/guardsquare/proguard/download_file?file_path=com%2Fguardsquare%2Fproguard-ant%2F7.0.0%2Fproguard-ant-7.0.0.jar), [proguard-base-7.0.0.jar](https://bintray.com/guardsquare/proguard/download_file?file_path=com%2Fguardsquare%2Fproguard-base%2F7.0.0%2Fproguard-base-7.0.0.jar), and [proguard-core-7.0.0.jar](https://bintray.com/guardsquare/proguard/download_file?file_path=com%2Fguardsquare%2Fproguard-core%2F7.0.0%2Fproguard-core-7.0.0.jar) from JCenter, and then specify something like this in your build.xml:

    <taskdef resource="proguard/ant/task.properties"
     classpath="/somepath/proguard-ant-7.0.0.jar:/somepath/proguard-base-7.0.0.jar:/somepath/proguard-core-7.0.0.jar" />

**Comment by giangiunta** [comment]
Thanks a lot for the information provided.

Looking forward to next update then.

**Comment by MikOfClassX** [comment]
+1

**Comment by emm87j** [comment]
Is this resolved yet?

**Comment by stmax82** [comment]
@emm87j nope :/

**Comment by mrjameshamilton** [comment]
Hi @stmax82, @emm87j, @MikOfClassX, @giangiunta, @rjahn!

We've fixed the packaging of the ant plugin on master. It'll appear in the next ProGuard release but you can already build this yourself: https://github.com/Guardsquare/proguard#-building-proguard

Note that the ant plugin artifact is now: `lib/proguard-ant.jar`

**Comment by JE4GLE** [comment]
@mrjameshamilton I'm using a self-built version from 1 hour ago and still getting the same error. My taskdef looks like this:
`<taskdef resource="${proguard.path}/ant/task.properties" classpath="${proguard.path}/lib/proguard-ant.jar" />`

I've already checked, that `${proguard.path}` refers to the correct folder.
Also, task.properties wasn't present in the /ant folder and I had to copy it manually from /ant/src/src/proguard/ant.

**Comment by mrjameshamilton** [comment]
Hi @JE4GLE, the `task.properties` file should be accessible from inside the `proguard-ant.jar`; this should work:

```
<taskdef resource="proguard/ant/task.properties" classpath="${proguard.path}/lib/proguard-ant.jar" />
```
